---
- name: Create Config Directory
  become: false
  file:
    path: "{{ local_user_homedir }}/.todo"
    state: directory
    owner: "{{ local_user_username }}"
    mode: 0755

- name: Create Data Directory
  become: false
  file:
    path: "{{ todo_data_directory }}"
    state: directory
    owner: "{{ local_user_username }}"
    mode: 0755

- name: Configure Todo
  become: false
  template:
    src: config.j2
    dest: "{{ local_user_homedir }}/.todo/config"
    mode: 0644

- name: "Create Todo Bash Alias ({{ todo_bash_alias }})"
  become: false
  lineinfile:
    path: "{{ local_user_homedir }}/.bash_aliases"
    regexp: "^alias {{ todo_bash_alias }}=.*$"
    line: "alias {{ todo_bash_alias }}='todo'"
    state: present
    create: yes
  when: todo_install_bash_alias

